#!/usr/bin/env bash

set -euo pipefail

main() {
  local tarball_path version

  while [ "${#}" != 0 ]; do
    case "${1}" in
      --version)
        version="${2}"
        shift 2
        ;;

      --tarballPath)
        tarball_path="${2}"
        shift 2
        ;;

      "")
        shift
        ;;

      *)
        echo "unknown argument \"${1}\""
        exit 1
    esac
  done

  if [[ -z "${version:-}" || -z "${tarball_path:-}" ]]; then
    echo "version and tarballPath are required required"
    exit 1
  fi

  dir="$(dirname "${tarball_path}")"
  artifact="$(basename "${tarball_path}")"

  echo "Running bionic test..."
  docker build -t test-bionic -f bionic.Dockerfile .
  docker run --rm -v "${dir}:/input" test-bionic --artifact "/input/${artifact}" --version "${version}"

  echo "Running jammy test..."
  docker build -t test-jammy -f jammy.Dockerfile .
  docker run --rm -v "${dir}:/input" test-jammy --artifact "/input/${artifact}" --version "${version}"
}

main "${@:-}"
