api = "0.7"

[buildpack]
  description = "A buildpack for installing the approriate Bundler version"
  homepage = "https://github.com/paketo-buildpacks/bundler"
  id = "paketo-buildpacks/bundler"
  keywords = ["ruby", "bundler"]
  name = "Paketo Buildpack for Bundler"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/bundler/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    checksum = "sha256:ea954773b124e9fc780080623b71a2124074734d5d0693b5dc603c7988684c7d"
    cpe = "cpe:2.3:a:bundler:bundler:2.7.1:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "bundler"
    purl = "pkg:generic/bundler@2.7.1?checksum=0ad5a002a879776b2a98be652f557ac8731be3353612d63fa4ef1b2706dc1e0b&download_url=https://rubygems.org/downloads/bundler-2.7.1.gem"
    source = "https://rubygems.org/downloads/bundler-2.7.1.gem"
    source-checksum = "sha256:0ad5a002a879776b2a98be652f557ac8731be3353612d63fa4ef1b2706dc1e0b"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    strip-components = 2
    uri = "https://artifacts.paketo.io/bundler/bundler-jammy-2.7.1-ea954773.tgz"
    version = "2.7.1"

  [[metadata.dependencies]]
    checksum = "sha256:467943b1637c4412ff4fb23d2df14b8860e60700212367475ad62b9a3bec4096"
    cpe = "cpe:2.3:a:bundler:bundler:2.7.2:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "bundler"
    purl = "pkg:generic/bundler@2.7.2?checksum=1decaf9e2e1acb91b6586a2925c8f3f6da2334a82731a62ff2ded1b83c283871&download_url=https://rubygems.org/downloads/bundler-2.7.2.gem"
    source = "https://rubygems.org/downloads/bundler-2.7.2.gem"
    source-checksum = "sha256:1decaf9e2e1acb91b6586a2925c8f3f6da2334a82731a62ff2ded1b83c283871"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    strip-components = 2
    uri = "https://artifacts.paketo.io/bundler/bundler-jammy-2.7.2-467943b1.tgz"
    version = "2.7.2"

  [[metadata.dependencies]]
    checksum = "sha256:de47178e5e3f93710cb3e206a6d6a3c61a48f470fdf4e37cd6577f004524d0d9"
    cpe = "cpe:2.3:a:bundler:bundler:4.0.7:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "bundler"
    purl = "pkg:generic/bundler@4.0.7?checksum=f8d8ab45cfdb755983de2c867a29680196a5340f6979f8a354b9244a49c20b17&download_url=https://rubygems.org/downloads/bundler-4.0.7.gem"
    source = "https://rubygems.org/downloads/bundler-4.0.7.gem"
    source-checksum = "sha256:f8d8ab45cfdb755983de2c867a29680196a5340f6979f8a354b9244a49c20b17"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    strip-components = 2
    uri = "https://artifacts.paketo.io/bundler/bundler-jammy-4.0.7-de47178e.tgz"
    version = "4.0.7"

  [[metadata.dependencies]]
    checksum = "sha256:589bb58bf59b11444c423cf153cc304f3b8cc816943e95ed9496782112e23c38"
    cpe = "cpe:2.3:a:bundler:bundler:4.0.8:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "bundler"
    purl = "pkg:generic/bundler@4.0.8?checksum=ad75e7903192d544bc62b377a35815d477459b7fbea6660991492e453e0be9b4&download_url=https://rubygems.org/downloads/bundler-4.0.8.gem"
    source = "https://rubygems.org/downloads/bundler-4.0.8.gem"
    source-checksum = "sha256:ad75e7903192d544bc62b377a35815d477459b7fbea6660991492e453e0be9b4"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    strip-components = 2
    uri = "https://artifacts.paketo.io/bundler/bundler-jammy-4.0.8-589bb58b.tgz"
    version = "4.0.8"

  [[metadata.dependency-constraints]]
    constraint = "2.*.*"
    id = "bundler"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "4.*.*"
    id = "bundler"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.jammy"

[[stacks]]
  id = "io.buildpacks.stacks.noble"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
