api = "0.7"

[buildpack]
  description = "A buildpack for installing the approriate Bundler version"
  homepage = "https://github.com/paketo-buildpacks/bundler"
  id = "paketo-buildpacks/bundler"
  keywords = ["ruby", "bundler"]
  name = "Paketo Buildpack for Bundler"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/bundler/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    checksum = "sha256:29b1057dfbc15e8eed4f8b255ba86ca0854c893b7226bcbcffce15adc11000d4"
    cpe = "cpe:2.3:a:bundler:bundler:2.7.1:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "bundler"
    purl = "pkg:generic/bundler@2.7.1?checksum=0ad5a002a879776b2a98be652f557ac8731be3353612d63fa4ef1b2706dc1e0b&download_url=https://rubygems.org/downloads/bundler-2.7.1.gem"
    source = "https://rubygems.org/downloads/bundler-2.7.1.gem"
    source-checksum = "sha256:0ad5a002a879776b2a98be652f557ac8731be3353612d63fa4ef1b2706dc1e0b"
    stacks = ["*"]
    strip-components = 2
    uri = "https://artifacts.paketo.io/bundler/bundler-resolute-2.7.1-29b1057d.tgz"
    version = "2.7.1"

  [[metadata.dependencies]]
    checksum = "sha256:005aa9febc690126846fc91bfb883cfd414b0548016ae2c18260d0f79acfe5c9"
    cpe = "cpe:2.3:a:bundler:bundler:2.7.2:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "bundler"
    purl = "pkg:generic/bundler@2.7.2?checksum=1decaf9e2e1acb91b6586a2925c8f3f6da2334a82731a62ff2ded1b83c283871&download_url=https://rubygems.org/downloads/bundler-2.7.2.gem"
    source = "https://rubygems.org/downloads/bundler-2.7.2.gem"
    source-checksum = "sha256:1decaf9e2e1acb91b6586a2925c8f3f6da2334a82731a62ff2ded1b83c283871"
    stacks = ["*"]
    strip-components = 2
    uri = "https://artifacts.paketo.io/bundler/bundler-resolute-2.7.2-005aa9fe.tgz"
    version = "2.7.2"

  [[metadata.dependencies]]
    checksum = "sha256:941291ea32410c8782b7c9f9093f308a483c7d108527f3137826bf0945d4e4b1"
    cpe = "cpe:2.3:a:bundler:bundler:4.0.21:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "bundler"
    purl = "pkg:generic/bundler@4.0.21?checksum=7cbf5499b426076aa16c8d28a59e4c2c3aad5a438402abcd961f0119f29f1dd0&download_url=https://rubygems.org/downloads/bundler-4.0.21.gem"
    source = "https://rubygems.org/downloads/bundler-4.0.21.gem"
    source-checksum = "sha256:7cbf5499b426076aa16c8d28a59e4c2c3aad5a438402abcd961f0119f29f1dd0"
    stacks = ["*"]
    strip-components = 2
    uri = "https://artifacts.paketo.io/bundler/bundler-resolute-4.0.21-941291ea.tgz"
    version = "4.0.21"

  [[metadata.dependencies]]
    checksum = "sha256:8fa0408313901d808c27605bddf3853e4098a4bc3dac9a4f15ef26311caffed8"
    cpe = "cpe:2.3:a:bundler:bundler:4.0.22:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "bundler"
    purl = "pkg:generic/bundler@4.0.22?checksum=d8d5ec84c8555e0af71db63ed7aee4d1a8fb839ec46d84212d61979242a5d75a&download_url=https://rubygems.org/downloads/bundler-4.0.22.gem"
    source = "https://rubygems.org/downloads/bundler-4.0.22.gem"
    source-checksum = "sha256:d8d5ec84c8555e0af71db63ed7aee4d1a8fb839ec46d84212d61979242a5d75a"
    stacks = ["*"]
    strip-components = 2
    uri = "https://artifacts.paketo.io/bundler/bundler-resolute-4.0.22-8fa04083.tgz"
    version = "4.0.22"

  [[metadata.dependency-constraints]]
    constraint = "2.*.*"
    id = "bundler"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "4.*.*"
    id = "bundler"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
