api = "0.7"

[buildpack]
  description = "A buildpack for installing the approriate Bundler version"
  homepage = "https://github.com/paketo-buildpacks/bundler"
  id = "paketo-buildpacks/bundler"
  keywords = ["ruby", "bundler"]
  name = "Paketo Buildpack for Bundler"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/bundler/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    checksum = "sha256:29b1057dfbc15e8eed4f8b255ba86ca0854c893b7226bcbcffce15adc11000d4"
    cpe = "cpe:2.3:a:bundler:bundler:2.7.1:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "bundler"
    purl = "pkg:generic/bundler@2.7.1?checksum=0ad5a002a879776b2a98be652f557ac8731be3353612d63fa4ef1b2706dc1e0b&download_url=https://rubygems.org/downloads/bundler-2.7.1.gem"
    source = "https://rubygems.org/downloads/bundler-2.7.1.gem"
    source-checksum = "sha256:0ad5a002a879776b2a98be652f557ac8731be3353612d63fa4ef1b2706dc1e0b"
    stacks = ["*"]
    strip-components = 2
    uri = "https://artifacts.paketo.io/bundler/bundler-resolute-2.7.1-29b1057d.tgz"
    version = "2.7.1"

  [[metadata.dependencies]]
    checksum = "sha256:005aa9febc690126846fc91bfb883cfd414b0548016ae2c18260d0f79acfe5c9"
    cpe = "cpe:2.3:a:bundler:bundler:2.7.2:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "bundler"
    purl = "pkg:generic/bundler@2.7.2?checksum=1decaf9e2e1acb91b6586a2925c8f3f6da2334a82731a62ff2ded1b83c283871&download_url=https://rubygems.org/downloads/bundler-2.7.2.gem"
    source = "https://rubygems.org/downloads/bundler-2.7.2.gem"
    source-checksum = "sha256:1decaf9e2e1acb91b6586a2925c8f3f6da2334a82731a62ff2ded1b83c283871"
    stacks = ["*"]
    strip-components = 2
    uri = "https://artifacts.paketo.io/bundler/bundler-resolute-2.7.2-005aa9fe.tgz"
    version = "2.7.2"

  [[metadata.dependencies]]
    checksum = "sha256:02902e4a30aea50a92badbfa606f6da8e9e45a4bcabfa65f4c2e84aaf2030548"
    cpe = "cpe:2.3:a:bundler:bundler:4.0.19:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "bundler"
    purl = "pkg:generic/bundler@4.0.19?checksum=b48056e4c77fb3853cc47775b5447ede44aaa4f53c32f168014ab4fe86587d47&download_url=https://rubygems.org/downloads/bundler-4.0.19.gem"
    source = "https://rubygems.org/downloads/bundler-4.0.19.gem"
    source-checksum = "sha256:b48056e4c77fb3853cc47775b5447ede44aaa4f53c32f168014ab4fe86587d47"
    stacks = ["*"]
    strip-components = 2
    uri = "https://artifacts.paketo.io/bundler/bundler-resolute-4.0.19-02902e4a.tgz"
    version = "4.0.19"

  [[metadata.dependencies]]
    checksum = "sha256:5ff89a9b35885df9ece64f34fee3baa7c0023076121e7ba930c7beb18f8c74b2"
    cpe = "cpe:2.3:a:bundler:bundler:4.0.20:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "bundler"
    purl = "pkg:generic/bundler@4.0.20?checksum=7978a8ac648767f5e635bc522445b79e80a52b907a39a36c2d8085ed6bc762ae&download_url=https://rubygems.org/downloads/bundler-4.0.20.gem"
    source = "https://rubygems.org/downloads/bundler-4.0.20.gem"
    source-checksum = "sha256:7978a8ac648767f5e635bc522445b79e80a52b907a39a36c2d8085ed6bc762ae"
    stacks = ["*"]
    strip-components = 2
    uri = "https://artifacts.paketo.io/bundler/bundler-resolute-4.0.20-5ff89a9b.tgz"
    version = "4.0.20"

  [[metadata.dependency-constraints]]
    constraint = "2.*.*"
    id = "bundler"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "4.*.*"
    id = "bundler"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
